# Generated by Django 5.0.4 on 2024-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.IntegerField()),
                ('expiry', models.IntegerField()),
                ('pharma_company', models.CharField(max_length=100)),
            ],
        ),
    ]
