# Generated by Django 5.0.4 on 2024-05-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(null=True, upload_to='medicine_image'),
        ),
    ]
