# Generated by Django 5.0.4 on 2024-05-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_medicine_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiry',
            field=models.DateField(),
        ),
    ]
